services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - job4j_devops_default

  kafka:
      image: confluentinc/cp-kafka:7.5.0
      container_name: kafka
      environment:
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      ports:
        - "9092:9092"
      networks:
        - job4j_devops_default
      depends_on:
        - zookeeper


  db_take2:
    image: postgres:16
    container_name: db_take2
    environment:
      POSTGRES_DB: job4j_devops
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - db_data_new:/var/lib/postgresql/data
    networks:
      - job4j_devops_default


  devops:
    build: .
    image: katyabahai/job4j_devops:v.1.0.1
    container_name: devops
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_take2:5432/job4j_devops
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"
    networks:
      - job4j_devops_default
    depends_on:
      - db_take2
      - kafka


networks:
  job4j_devops_default:
    external: true

volumes:
  db_data_new:


